./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/sched_module.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/timer.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/boot_module.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/haltprog.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/sched_module.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/os_startup.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/MOD_0.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/MOD_3.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/MOD_4.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/sample_int7.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/console_interr.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/disk_int.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_6.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/MOD_1.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/MOD_2.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_9.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_8.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_4.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_5.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_10.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_11.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_15.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_13.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/int_14.spl
./spl /root/Desktop/OperatingSystem/myexpos/Assignments/Stage25/exception_handler.spl
