./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/sched_module.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/timer.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/boot_module.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/haltprog.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/sched_module.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/os_startup.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/MOD_0.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/MOD_4.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/sample_int7.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/console_interr.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/disk_int.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/int_6.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/MOD_1.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/MOD_2.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/int_9.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/int_8.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/int_10.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/int_11.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/int_15.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/int_13.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/int_14.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage22:Assign3/exception_handler.spl
