./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/sched_module.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/timer.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/boot_module.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/haltprog.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/sched_module.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/os_startup.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/MOD_0.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/MOD_3.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/MOD_4.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/sample_int7.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/console_interr.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/disk_int.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_6.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/MOD_1.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/MOD_2.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_9.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_8.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_4.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_5.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_10.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_11.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_15.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_13.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/int_14.spl
./spl $HOME/OperatingSystem/myexpos/Assignments/Stage24/exception_handler.spl
