./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/sched_module.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/timer.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/boot_module.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/haltprog.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/sched_module.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/os_startup.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/MOD_0.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/MOD_4.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/sample_int7.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/console_interr.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/disk_int.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/int_6.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/MOD_1.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/MOD_2.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/int_9.spl
./spl /root/Desktop/myexpos/Assignments/Stage19:Assign2/exception_handler.spl
